### ISSUE TITLE
to_yaml not working with 1.9.4

### ISSUE THREAD

**Issue by denizin** [cloudtools/troposphere#759]
For some reason I keep getting this error when using the to_yaml function:

   print(t.to_yaml())
AttributeError: 'Template' object has no attribute 'to_yaml'

troposphere-1.9.4.egg-info

Did a pip install troposphere[policy] --upgrade

I don't see any of the cfn_flip stuff in the files.  I'm not sure why 1.9.4 doesn't have this when I use pip install.  

Thank you.

**Comment by markpeek** [comment]
The yaml support was added after 1.9.4. Please try github master for now. I was going to release 1.9.5 last weekend but there were some pending updates that delayed it.

**Comment by cwardcode** [comment]
I just pulled in the latest version, and it doesn't seem to be supported in 1.9.6 either. Was support for yaml fully removed?

**Comment by markpeek** [comment]
The feature needed to be reverted due to a regression (#762). 

I did provide an upstream [patch](https://github.com/awslabs/aws-cfn-template-flip/pull/22) to fix it but it has not been commented on.

**Comment by stilvoid** [comment]
@markpeek I've just merged in your PR. Apologies for the delay and thanks :)
